Virtual Arm for Impaired: usb_drv.c File Reference
usb_drv.c File Reference
This file contains the USB driver routines.
#include "config.h"
#include "conf_usb.h"
#include "usb_drv.h"
Functions
U8 usb_config_ep (U8 config0, U8 config1)
usb_configure_endpoint.
U8 usb_select_enpoint_interrupt (void)
usb_select_endpoint_interrupt.
U8 usb_send_packet (U8 ep_num, U8 *tbuf, U8 data_length)
usb_send_packet.
U8 usb_read_packet (U8 ep_num, U8 *rbuf, U8 data_length)
usb_read_packet.
void usb_halt_endpoint (U8 ep_num)
usb_halt_endpoint.
U8 usb_init_device (void)
usb_init_device.
U8 host_config_pipe (U8 config0, U8 config1)
--------------------------------------------------------- ------------------ HOST --------------------------------- ---------------------------------------------------------
U8 host_determine_pipe_size (U16 size)
host_determine_pipe_size.
void host_disable_all_pipe (void)
host_disable_all_pipe.
U8 usb_get_nb_pipe_interrupt (void)
Returns the pipe number that generates a USB communication interrupt.
Detailed Description
This file contains the USB driver routines.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: AT90USB1287, AT90USB1286, AT90USB647, AT90USB646
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file usb_drv.c.
Function Documentation
U8 usb_config_ep (U8 config0, U8 config1)
usb_configure_endpoint.
This function configures an endpoint with the selected type.
Parameters:
config0
config1
Returns:
Is_endpoint_configured.
Definition at line 67 of file usb_drv.c.
References Is_endpoint_configured, Usb_allocate_memory, and Usb_enable_endpoint.
{
    Usb_enable_endpoint();
    UECFG0X = config0;
    UECFG1X = (UECFG1X & (1<<ALLOC)) | config1;
    Usb_allocate_memory();
    return (Is_endpoint_configured());
}
U8 usb_select_enpoint_interrupt (void)
usb_select_endpoint_interrupt.
This function select the endpoint where an event occurs and returns the number of this endpoint. If no event occurs on the endpoints, this function returns 0.
Parameters:
none
Returns:
endpoint number.
Definition at line 87 of file usb_drv.c.
References ep_num, MAX_EP_NB, and Usb_interrupt_flags.
{
U8 interrupt_flags;
U8 ep_num;
   ep_num = 0;
   interrupt_flags = Usb_interrupt_flags();
   while(ep_num < MAX_EP_NB)
   {
      if (interrupt_flags & 1)
      {
         return (ep_num);
      }
      else
      {
         ep_num++;
         interrupt_flags = interrupt_flags >> 1;
      }
   }
   return 0;
}
U8 usb_send_packet (U8 ep_num, U8 * tbuf, U8 data_length)
usb_send_packet.
This function moves the data pointed by tbuf to the selected endpoint fifo and sends it through the USB.
Parameters:
ep_num number of the addressed endpoint
*tbuf address of the first data to send
data_length number of bytes to send
Returns:
address of the next U8 to send.
Example: usb_send_packet(3,&first_data,0x20); // send packet on the endpoint #3 while(!(Usb_tx_complete)); // wait packet ACK'ed by the Host Usb_clear_tx_complete(); // acknowledge the transmit
Note: tbuf is incremented of 'data_length'.
Definition at line 130 of file usb_drv.c.
References Is_usb_write_enabled, Usb_select_endpoint, and Usb_write_byte.
{
U8 remaining_length;
   remaining_length = data_length;
   Usb_select_endpoint(ep_num);
   while(Is_usb_write_enabled() && (0 != remaining_length))
   {
      Usb_write_byte(*tbuf);
      remaining_length--;
      tbuf++;
   }
   return remaining_length;
}
U8 usb_read_packet (U8 ep_num, U8 * rbuf, U8 data_length)
usb_read_packet.
This function moves the data stored in the selected endpoint fifo to the address specified by *rbuf.
Parameters:
ep_num number of the addressed endpoint
*rbuf aaddress of the first data to write with the USB data
data_length number of bytes to read
Returns:
address of the next U8 to send.
Example: while(!(Usb_rx_complete)); // wait new packet received usb_read_packet(4,&first_data,usb_get_nb_byte); // read packet from ep 4 Usb_clear_rx(); // acknowledge the transmit
Note: rbuf is incremented of 'data_length'.
Definition at line 165 of file usb_drv.c.
References Is_usb_read_enabled, Usb_read_byte, and Usb_select_endpoint.
{
U8 remaining_length;
   remaining_length = data_length;
   Usb_select_endpoint(ep_num);
   while(Is_usb_read_enabled() && (0 != remaining_length))
   {
      *rbuf = Usb_read_byte();
      remaining_length--;
      rbuf++;
   }
   return remaining_length;
}
void usb_halt_endpoint (U8 ep_num)
usb_halt_endpoint.
This function sends a STALL handshake for the next Host request. A STALL handshake will be send for each next request untill a SETUP or a Clear Halt Feature occurs for this endpoint.
Parameters:
ep_num number of the addressed endpoint
Returns:
none
Definition at line 191 of file usb_drv.c.
References Usb_enable_stall_handshake, and Usb_select_endpoint.
{
   Usb_select_endpoint(ep_num);
   Usb_enable_stall_handshake();
}
U8 usb_init_device (void)
usb_init_device.
This function initializes the USB device controller and configures the Default Control Endpoint.
Parameters:
none
Returns:
status
Definition at line 207 of file usb_drv.c.
References DIRECTION_OUT, EP_CONTROL, FALSE, Is_usb_endpoint_enabled, Is_usb_id_device, NYET_DISABLED, ONE_BANK, SIZE_64, SIZE_8, TYPE_CONTROL, usb_configure_endpoint, Usb_select_device, and Usb_select_endpoint.
Referenced by usb_general_interrupt(), and usb_start_device().
{
   Usb_select_device();
   if(Is_usb_id_device())
   {
      Usb_select_endpoint(EP_CONTROL);
      if(!Is_usb_endpoint_enabled())
      {
#if (USB_LOW_SPEED_DEVICE==DISABLE)
         return usb_configure_endpoint(EP_CONTROL,    \
                                TYPE_CONTROL,  \
                                DIRECTION_OUT, \
                                SIZE_64,       \
                                ONE_BANK,      \
                                NYET_DISABLED);
#else
         return usb_configure_endpoint(EP_CONTROL,    \
                                TYPE_CONTROL,  \
                                DIRECTION_OUT, \
                                SIZE_8,       \
                                ONE_BANK,      \
                                NYET_DISABLED);
#endif
      }
   }
   return FALSE;
}
U8 host_config_pipe (U8 config0, U8 config1)
--------------------------------------------------------- ------------------ HOST --------------------------------- ---------------------------------------------------------
usb_configure_pipe.
This function configures a pipe with the selected type.
Parameters:
config0
config1
Returns:
Is_endpoint_configured.
Definition at line 252 of file usb_drv.c.
References Host_allocate_memory, Host_enable_pipe, and Is_pipe_configured.
{
    Host_enable_pipe();
    UPCFG0X = config0;
    UPCFG1X = config1;
    Host_allocate_memory();
    return (Is_pipe_configured());
}
U8 host_determine_pipe_size (U16 size)
host_determine_pipe_size.
This function returns the size configuration register value according to the endpint size detected inthe device enumeration process.
Returns:
pipe size register value.
Definition at line 268 of file usb_drv.c.
References SIZE_1024, SIZE_128, SIZE_16, SIZE_256, SIZE_32, SIZE_512, SIZE_64, and SIZE_8.
{
        if(size <= 8  ) {return (SIZE_8   );}
   else if(size <= 16 ) {return (SIZE_16  );}
   else if(size <= 32 ) {return (SIZE_32  );}
   else if(size <= 64 ) {return (SIZE_64  );}
   else if(size <= 128) {return (SIZE_128 );}
   else if(size <= 256) {return (SIZE_256 );}
   else if(size <= 512) {return (SIZE_512 );}
   else                 {return (SIZE_1024);}
}
void host_disable_all_pipe (void)
host_disable_all_pipe.
This function disable all pipes for the host controller Usefull to execute upon device disconnection.
Returns:
none.
Definition at line 288 of file usb_drv.c.
References Host_disable_pipe, Host_reset_pipe, Host_select_pipe, and Host_unallocate_memory.
Referenced by usb_general_interrupt().
{
U8 i;
   for (i=0;i<7;i++)
   {
      Host_reset_pipe(i);
      Host_select_pipe(i);
      Host_unallocate_memory();
      Host_disable_pipe();
   }
}
U8 usb_get_nb_pipe_interrupt (void)
Returns the pipe number that generates a USB communication interrupt.
This function sould be called only when an interrupt has been detected. Otherwize the return value is incorect
Parameters:
none
Returns:
pipe_number
Definition at line 309 of file usb_drv.c.
References Host_get_pipe_interrupt, and MAX_EP_NB.
{
U8 interrupt_flags;
U8 i;
   interrupt_flags = Host_get_pipe_interrupt();
   for(i=0;i< MAX_EP_NB;i++)
   {
      if (interrupt_flags & (1<<i))
      {
         return (i);
      }
   }
   // This return should never occurs ....
   return MAX_EP_NB+1;
}