Virtual Arm for Impaired: sensors.c File Reference
sensors.c File Reference
This file contains all sensor code.
#include "sensors.h"
Functions
bit is_mouse_event (void)
This function checks the board interface and fills the HID mouse report.
bit Default_func (void)
This function defines state 0: Default State.
bit Mov_count_func (void)
This function defines state 1: Movement Countdown State.
bit Mov_press_func (void)
This function defines state 2: Movement Press State.
bit Mov_touch_func (void)
This function defines state 3: Movement Touch State.
bit Button_wait_func (void)
This function defines state 4: Button Wait State.
bit Scroll_func (void)
This function defines state 5: Scroll State.
bit Maybe_slow_cursor (void)
This function slows the cursor down if Slow_cursor is TRUE.
bit Maybe_left_holddown (void)
This function holds down the left button if Left_holddown is TRUE.
bit is_movement_sensor (U8 sensor)
This function checks whether a sensor is a movement sensor.
bit is_button_sensor (U8 sensor)
This function checks whether a sensor is a button sensor.
U8 adc_reader (U8 channel)
This function reads the chosen ADC channel.
void Read_sensors (void)
This function updates Invalue.
void Calibrate (void)
This function updates Zerovalue by copying Invalue.
bit is_sensor_step (U8 sensor, U8 step)
This function checks whether a sensor's value is larger than a given step threshold, relative to Zerovalue.
bit is_sensor_active (U8 sensor)
This function checks whether a sensor if active.
bit is_more_active (U8 upper, U8 lower)
This function checks which sensor is more active.
U8 find_active_sensor (void)
This function runs through the read sensor values and returns the most active sensor, if any.
U8 check_nearby_sensor (U8 sensor)
This function returns an active nearby sensor, if any.
void Check_hang (U8 sensor)
This function re-calibrates a hanging sensor by checking opposite cheek.
void Inc_speed (U8 sensor)
This function checks sensor pressure for speed increase.
void Modify_report (U8 sensor)
This function modifies g_hid_mouse_report.
Variables
U8 State = DEFAULT_STATE
State variable, to memorize across tasks.
U16 State_counter = 0
Generic global counter to stay in a state a number of tasks.
bit Slow_cursor = FALSE
If TRUE, cursor speed may be decreased by skipping tasks.
bit Left_holddown = FALSE
If TRUE, the left mouse button is held down.
bit Report_filled = FALSE
If TRUE, there is a mouse event.
U8 g_hid_mouse_report [4]
Mouse report, defined in mouse_task.c.
U8 Zerovalue [8] = {0}
Calibration values of sensors (i.e., reference level).
U8 Invalue [8] = {0}
Read values of sensors, to be compared against the calibration values.
U8 Active_sensor = 0
Number of currently active sensor.
U8 Neighbor_sensor = 0
Number of active neighbor sensor.
bit Nearby_sensors [8][8]
Matrix of adjacent sensors.
Detailed Description
This file contains all sensor code.
Author:
Bastian S. Solem and Vegard Øye
Definition in file sensors.c.
Function Documentation
bit is_mouse_event (void)
This function checks the board interface and fills the HID mouse report.
Divided into states to remember things across tasks. The current state is represented by the global variable State, and the actions to be carried out are placed in state functions. Thus, this function calls one of Default_func, Mov_count_func, Mov_press_func, Mov_touch_func, Button_wait_func and Scroll_func. For a detailed description of each state, see their state function.
It also calls Maybe_slow_cursor and Maybe_left_holddown to slow down the cursor and/or hold the left mouse button down.
Returns:
TRUE if an event occurs. In this case, the report is filled.
FALSE if no event.
Definition at line 78 of file sensors.c.
References Button_wait_func(), BUTTON_WAIT_STATE, Default_func(), DEFAULT_STATE, FALSE, Hid_mouse_report_reset, Maybe_left_holddown(), Maybe_slow_cursor(), Mov_count_func(), MOV_COUNT_STATE, Mov_press_func(), MOV_PRESS_STATE, Mov_touch_func(), MOV_TOUCH_STATE, Read_sensors(), Report_filled, Scroll_func(), SCROLL_STATE, and State.
Referenced by mouse_task().
{
   // Always reset the HID mouse report. Always.
   Hid_mouse_report_reset();
   Read_sensors();
   switch(State) {
      case DEFAULT_STATE :
         Report_filled = Default_func();
         break;
      case MOV_COUNT_STATE :
         Report_filled = Mov_count_func();
         break;
      case MOV_PRESS_STATE :
         Report_filled = Mov_press_func();
         break;
      case MOV_TOUCH_STATE :
         Report_filled = Mov_touch_func();
         break;
      case BUTTON_WAIT_STATE :
         Report_filled = Button_wait_func();
         break;
      case SCROLL_STATE :
         Report_filled = Scroll_func();
         break;
      default :
         State = DEFAULT_STATE;
         Report_filled = FALSE;
         break;
   }
   Report_filled = Maybe_slow_cursor();
   Report_filled = Maybe_left_holddown();
   return Report_filled;
}
bit Default_func (void)
This function defines state 0: Default State.
Reads sensors and checks for trigger event. If a movement sensor is active, enter Movement Countdown State; if a button sensor is active, enter Button Wait State. The mouse report is filled before entering these states, and the active sensor is stored in Active_sensor.
If no sensors are active, re-calibrate now and then.
This function uses State_counter.
This function sets Slow_cursor.
This function may change Left_holddown.
Returns:
TRUE if a sensor is active and the report is filled.
FALSE otherwise.
Definition at line 140 of file sensors.c.
References Active_sensor, BUTTON_WAIT_STATE, Calibrate(), FALSE, find_active_sensor(), is_button_sensor(), is_movement_sensor(), Left_holddown, Modify_report(), MOV_COUNT_STATE, Neighbor_sensor, NO_SENSOR, Slow_cursor, State, State_counter, and TRUE.
Referenced by is_mouse_event().
                       {
   Active_sensor = NO_SENSOR;
   Neighbor_sensor = NO_SENSOR;
   // Check for trigger event
   Active_sensor = find_active_sensor();
   if(is_button_sensor(Active_sensor)) { // Buttons cheek
      if(Left_holddown) {
         Left_holddown = FALSE;
         Active_sensor = NO_SENSOR;
      }
      State_counter = 0;
      State = BUTTON_WAIT_STATE;
      return TRUE;
   }
   else if(is_movement_sensor(Active_sensor)) { // Movements cheek
      Modify_report(Active_sensor);
      State_counter = 0;
      Slow_cursor = TRUE;
      State = MOV_COUNT_STATE;
      return TRUE;
   }
   // No event, re-calibrate every 250 task
   if(State_counter > 250) {
      State_counter = 0;
      Calibrate();
   }
   State_counter++;
   return FALSE;
}
bit Mov_count_func (void)
This function defines state 1: Movement Countdown State.
Enter Movement Touch State on release or, if the user is still pressing after 250 tasks, Movement Press State. Active_sensor holds the sensor to be checked.
This function uses State_counter.
This function may change Slow_cursor.
Returns:
TRUE while moving sensor.
FALSE otherwise.
Definition at line 187 of file sensors.c.
References Active_sensor, FALSE, is_sensor_active(), Modify_report(), MOV_PRESS_STATE, MOV_TOUCH_STATE, Slow_cursor, State, State_counter, and TRUE.
Referenced by is_mouse_event().
{
   State_counter++;
   if(!is_sensor_active(Active_sensor) && State_counter > 10) {
      State_counter = 0;
      State = MOV_TOUCH_STATE;
      return TRUE;
   }
   else if(State_counter > 250) {
      State_counter = 0;
      Slow_cursor = FALSE;
      State = MOV_PRESS_STATE;
      return TRUE;
   }
   Modify_report(Active_sensor);
   return TRUE;
}
bit Mov_press_func (void)
This function defines state 2: Movement Press State.
Reads active movement sensors, checks for hang, and modifies the mouse report with pressure-dependent speeds. When movement sensors are no longer active, enter Default State.
Returns:
TRUE if a movement sensor is active.
FALSE otherwise.
Definition at line 215 of file sensors.c.
References Active_sensor, Check_hang(), check_nearby_sensor(), DEFAULT_STATE, FALSE, find_active_sensor(), Inc_speed(), is_movement_sensor(), Modify_report(), Neighbor_sensor, State, and TRUE.
Referenced by is_mouse_event().
{
   Active_sensor = find_active_sensor();
   if(is_movement_sensor(Active_sensor)) {
      Neighbor_sensor = check_nearby_sensor(Active_sensor);
      Check_hang(Active_sensor);
      Modify_report(Active_sensor);
      Modify_report(Neighbor_sensor);
      Inc_speed(Active_sensor);
      Inc_speed(Neighbor_sensor);
      return TRUE;
   }
   State = DEFAULT_STATE;
   return FALSE;
}
bit Mov_touch_func (void)
This function defines state 3: Movement Touch State.
Like Movement Countdown State, move slowly in the direction of Active_sensor. After 1000 tasks, move faster.
Exiting the state happens in three ways:
If the current sensor is touched again, stop the movement and enter Button Wait State. If a button sensor is touched, do the same.
If another movement sensor is touched, enter Movement Countdown State.
This function uses State_counter.
This function may change Slow_cursor.
This function may change Left_holddown.
Returns:
TRUE while in this state.
FALSE when a button sensor is touched.
Definition at line 259 of file sensors.c.
References Active_sensor, BUTTON_WAIT_STATE, FALSE, find_active_sensor(), is_button_sensor(), is_movement_sensor(), Left_holddown, Modify_report(), MOV_COUNT_STATE, NO_SENSOR, Slow_cursor, State, State_counter, and TRUE.
Referenced by is_mouse_event().
{
   if(Left_holddown) {
      Left_holddown = !is_button_sensor(find_active_sensor());
   }
   if(is_button_sensor(find_active_sensor()) ||
      Active_sensor == find_active_sensor()) {
      Active_sensor = NO_SENSOR;
      State_counter = 0;
      State = BUTTON_WAIT_STATE;
      return FALSE;
   }
   else if(is_movement_sensor(find_active_sensor())) {
      Active_sensor = find_active_sensor();
      State_counter = 0;
      State = MOV_COUNT_STATE;
      return TRUE;
   }
   if(State_counter <= 1000) {
      State_counter++;
   }
   else { // Past first 1000 tasks, move faster
      Slow_cursor = FALSE;
   }
   Modify_report(Active_sensor);
   return TRUE;
}
bit Button_wait_func (void)
This function defines state 4: Button Wait State.
Produce one click and wait. The precise behavior depends on the value the previous task has set Active_sensor to:
If Active_sensor is NO_SENSOR, don't produce a click; just enter Default State on release (but no earlier than 100 tasks).
If Active_sensor is a button, produce a click on quick release and enter Default State. However, if the button is held for more than 100 tasks, enter a different state:
If Active_sensor is LCLICK_SENSOR, activate holddown of the left mouse button and enter Default State.
If Active_sensor is RCLICK_SENSOR, enter Scroll State.
This function uses State_counter.
This function may change Left_holddown.
Returns:
TRUE when producing a click.
FALSE while waiting.
Definition at line 315 of file sensors.c.
References Active_sensor, DEFAULT_STATE, FALSE, find_active_sensor(), is_button_sensor(), LCLICK_SENSOR, Left_holddown, Modify_report(), NO_SENSOR, SCROLL_STATE, State, State_counter, and TRUE.
Referenced by is_mouse_event().
{
   switch(Active_sensor) {
      case NO_SENSOR :
         State_counter++;
         if(State_counter > 100 &&
            !is_button_sensor(find_active_sensor())) {
            State_counter = 0;
            State = DEFAULT_STATE;
         }
         return FALSE;
      default : // Button
         if(!is_button_sensor(find_active_sensor())) {
            if(State_counter > 100) {
               Left_holddown = FALSE;
               if(Active_sensor == LCLICK_SENSOR) {
                  Left_holddown = TRUE;
               }
               else {
                  State = SCROLL_STATE;
                  return FALSE;
               }
            }
            Modify_report(Active_sensor);
            State_counter = 0;
            State = DEFAULT_STATE;
            return TRUE;
         }
         State_counter++;
         return FALSE;
   }
}
bit Scroll_func (void)
This function defines state 5: Scroll State.
UP_SENSOR scrolls up and DOWN_SENSOR scrolls down. Scroll signals are sent only every 50 task to limit speed.
Exits to Button Wait State when a button is pressed.
This function uses State_counter.
Returns:
TRUE while scrolling.
FALSE otherwise.
Definition at line 363 of file sensors.c.
References Active_sensor, BUTTON_WAIT_STATE, DOWN_SENSOR, FALSE, find_active_sensor(), Hid_mouse_report_scroll_down, Hid_mouse_report_scroll_up, is_button_sensor(), LCLICK_SENSOR, NO_SENSOR, RCLICK_SENSOR, State, State_counter, TRUE, and UP_SENSOR.
Referenced by is_mouse_event().
                      {
   Active_sensor = find_active_sensor();
   State_counter++;
   if(State_counter > 50 || is_button_sensor(Active_sensor)) {
      State_counter = 0;
      switch(Active_sensor) {
         case UP_SENSOR : // PF1
            Hid_mouse_report_scroll_up();
            return TRUE;
         case DOWN_SENSOR : // PF5
            Hid_mouse_report_scroll_down();
            return TRUE;
         case RCLICK_SENSOR : // PF6
            Active_sensor = NO_SENSOR;
            State_counter = 0;
            State = BUTTON_WAIT_STATE;
            return TRUE;
         case LCLICK_SENSOR : // PF7
            Active_sensor = NO_SENSOR;
            State_counter = 0;
            State = BUTTON_WAIT_STATE;
            return FALSE;
      }
   }
   return FALSE;
}
bit Maybe_slow_cursor (void)
This function slows the cursor down if Slow_cursor is TRUE.
If so, and if State_counter is not a multiple of 5, reset byte 1 and 2 in g_hid_mouse_report.
This function uses State_counter.
Returns:
FALSE if movement has been decimated.
TRUE otherwise.
Definition at line 405 of file sensors.c.
References FALSE, g_hid_mouse_report, Slow_cursor, State_counter, and TRUE.
Referenced by is_mouse_event().
{
   if(Slow_cursor && State_counter % 5 != 0) {
      g_hid_mouse_report[1] = 0;
      g_hid_mouse_report[2] = 0;
      return FALSE;
   }
   return TRUE;
}
bit Maybe_left_holddown (void)
This function holds down the left button if Left_holddown is TRUE.
Returns:
TRUE if the button is held down.
Report_filled otherwise.
Definition at line 419 of file sensors.c.
References LCLICK_SENSOR, Left_holddown, Modify_report(), and Report_filled.
Referenced by is_mouse_event().
{
   if(Left_holddown) {
      Modify_report(LCLICK_SENSOR);
   }
   return (Report_filled || Left_holddown);
}
bit is_movement_sensor (U8 sensor)
This function checks whether a sensor is a movement sensor.
That is, if it is one of DOWN_SENSOR, LEFT_SENSOR, RIGHT_SENSOR or UP_SENSOR.
Parameters:
sensor The sensor to be checked.
Returns:
TRUE if a movement sensor.
FALSE otherwise.
Definition at line 436 of file sensors.c.
References DOWN_SENSOR, FALSE, LEFT_SENSOR, RIGHT_SENSOR, TRUE, and UP_SENSOR.
Referenced by Check_hang(), Default_func(), is_sensor_active(), Mov_press_func(), Mov_touch_func(), and Read_sensors().
{
   if(sensor == DOWN_SENSOR) {
      return TRUE;
   }
   else if(sensor == LEFT_SENSOR) {
      return TRUE;
   }
   else if(sensor == RIGHT_SENSOR) {
      return TRUE;
   }
   else if(sensor == UP_SENSOR) {
      return TRUE;
   }
   return FALSE;
}
bit is_button_sensor (U8 sensor)
This function checks whether a sensor is a button sensor.
That is, if it is one of LCLICK_SENSOR or RCLICK_SENSOR.
Parameters:
sensor The sensor to be checked.
Returns:
TRUE if a button sensor.
FALSE otherwise.
Definition at line 461 of file sensors.c.
References FALSE, LCLICK_SENSOR, RCLICK_SENSOR, and TRUE.
Referenced by Button_wait_func(), Check_hang(), Default_func(), is_sensor_active(), Mov_touch_func(), Read_sensors(), and Scroll_func().
{
   if(sensor == LCLICK_SENSOR) {
      return TRUE;
   }
   else if(sensor == RCLICK_SENSOR) {
      return TRUE;
   }
   return FALSE;
}
U8 adc_reader (U8 channel)
This function reads the chosen ADC channel.
Todo:
Can be rewritten with an init. The wait must then also be rewritten to wait for ADSC clear.
Parameters:
channel The channel to be read.
Returns:
The value of the channel.
Definition at line 480 of file sensors.c.
References Adc_get_8_bits_result, Clear_adc_flag, Enable_adc, Is_adc_conv_finished, Set_prescaler, and Start_conv_channel.
Referenced by mouse_task_init(), and Read_sensors().
{
   Clear_adc_flag();
   Enable_adc();
   Set_prescaler(6);
   Start_conv_channel(channel); // Normal conv. uses 13 clock cycles
   while(!Is_adc_conv_finished()); // Wait for ADC conv.
   return Adc_get_8_bits_result();
}
void Read_sensors (void)
This function updates Invalue.
Definition at line 491 of file sensors.c.
References ADC_END_CHANNEL, adc_reader(), ADC_START_CHANNEL, Invalue, is_button_sensor(), and is_movement_sensor().
Referenced by is_mouse_event().
{
   U8 sensor;
   for(sensor = ADC_START_CHANNEL; sensor <= ADC_END_CHANNEL; sensor++) {
      if(is_movement_sensor(sensor) || is_button_sensor(sensor)) {
         Invalue[sensor] = adc_reader(sensor);
      }
   }
}
void Calibrate (void)
This function updates Zerovalue by copying Invalue.
Remember to call Read_sensors to get fresh results.
Definition at line 504 of file sensors.c.
References ADC_END_CHANNEL, ADC_START_CHANNEL, Invalue, and Zerovalue.
Referenced by Check_hang(), and Default_func().
                     {
   U8 sensor;
   for(sensor = ADC_START_CHANNEL; sensor <= ADC_END_CHANNEL; sensor++) {
      Zerovalue[sensor] = Invalue[sensor];
   }
}
bit is_sensor_step (U8 sensor, U8 step)
This function checks whether a sensor's value is larger than a given step threshold, relative to Zerovalue.
Invalue[sensor] > (Zerovalue[sensor] + step)
Parameters:
sensor The sensor to be measured.
step The step: STEP, STEP2, ..., STEP6.
Returns:
TRUE if the value is larger.
FALSE if not.
Definition at line 522 of file sensors.c.
References Invalue, and Zerovalue.
Referenced by Inc_speed(), and is_sensor_active().
{
   return (Invalue[sensor] > (Zerovalue[sensor] + step));
}
bit is_sensor_active (U8 sensor)
This function checks whether a sensor if active.
Uses STEP for movement sensors and STEP2 for button sensors.
Remember to call Read_sensors to get fresh results.
Parameters:
sensor The sensor to be checked.
Returns:
TRUE if active.
FALSE if not active.
Definition at line 536 of file sensors.c.
References FALSE, is_button_sensor(), is_movement_sensor(), is_sensor_step(), STEP, and STEP2.
Referenced by Check_hang(), is_more_active(), and Mov_count_func().
{
   if(is_button_sensor(sensor)) { // Buttons cheek
      return is_sensor_step(sensor, STEP2);
   }
   else if(is_movement_sensor(sensor)) { // Movements cheek
      return is_sensor_step(sensor, STEP);
   }
   return FALSE;
}
bit is_more_active (U8 upper, U8 lower)
This function checks which sensor is more active.
Remember to call Read_sensors to get fresh results.
Parameters:
upper The sensor to be compared.
lower The sensor to compare against.
Returns:
TRUE if upper is more active.
FALSE otherwise.
Definition at line 556 of file sensors.c.
References Invalue, and is_sensor_active().
Referenced by check_nearby_sensor(), and find_active_sensor().
{
   return ((Invalue[upper] > Invalue[lower] &&
            is_sensor_active(upper)));
}
U8 find_active_sensor (void)
This function runs through the read sensor values and returns the most active sensor, if any.
Remember to call Read_sensors to get fresh results.
Returns:
The number of the active sensor, NO_SENSOR if not found.
Definition at line 568 of file sensors.c.
Referenced by Button_wait_func(), Default_func(), Mov_press_func(), Mov_touch_func(), and Scroll_func().
{
   U8 sensor = NO_SENSOR;
   U8 i;
   for(i = ADC_START_CHANNEL; i <= ADC_END_CHANNEL; i++) {
      if(is_more_active(i, sensor)) {
         sensor = i;
      }
   }
   return sensor;
}
U8 check_nearby_sensor (U8 sensor)
This function returns an active nearby sensor, if any.
Remember to call Read_sensors to get fresh results.
Parameters:
sensor The sensor whose nearby sensors are to be checked.
Returns:
The most active nearby sensor found.
NO_SENSOR if no nearby sensors are active.
Definition at line 588 of file sensors.c.
References ADC_END_CHANNEL, is_more_active(), Nearby_sensors, and NO_SENSOR.
Referenced by Mov_press_func().
{
   U8 neighbor = NO_SENSOR;
   U8 i;
   for(i = sensor + 1; i <= ADC_END_CHANNEL; i++) {
      if(Nearby_sensors[sensor][i] && is_more_active(i, neighbor)) {
         neighbor = i;
      }
   }
   return neighbor;
}
void Check_hang (U8 sensor)
This function re-calibrates a hanging sensor by checking opposite cheek.
Doesn't do anything if passed NO_SENSOR.
Remember to call Read_sensors to get fresh results.
Parameters:
sensor The sensor to be checked.
Definition at line 607 of file sensors.c.
References ADC_END_CHANNEL, ADC_START_CHANNEL, Calibrate(), is_button_sensor(), is_movement_sensor(), and is_sensor_active().
Referenced by Mov_press_func().
{
   U8 i;
   for(i = ADC_START_CHANNEL; i <= ADC_END_CHANNEL; i++) {
      if(is_sensor_active(i) &&
         ((is_movement_sensor(sensor) && is_button_sensor(i)) ||
          (is_button_sensor(sensor) && is_movement_sensor(i)))) {
         Calibrate();
         return;
      }
   }
}
void Inc_speed (U8 sensor)
This function checks sensor pressure for speed increase.
If pressure > STEP3, ..., STEP6 (relative to Zerovalue), call Modify_report() to increase cursor speed.
Remember to call Read_sensors to get fresh results.
Parameters:
sensor The sensor to be measured.
Definition at line 628 of file sensors.c.
References is_sensor_step(), Modify_report(), STEP3, STEP4, STEP5, and STEP6.
Referenced by Mov_press_func().
{
   if(is_sensor_step(sensor, STEP3)) {
      Modify_report(sensor);
   }
   if(is_sensor_step(sensor, STEP4)) {
      Modify_report(sensor);
   }
   if(is_sensor_step(sensor, STEP5)) {
      Modify_report(sensor);
   }
   if(is_sensor_step(sensor, STEP6)) {
      Modify_report(sensor);
   }
}
void Modify_report (U8 sensor)
This function modifies g_hid_mouse_report.
Parameters:
sensor The sensor whose corresponding action is to happen. If NO_SENSOR, no action is taken.
Definition at line 648 of file sensors.c.
References DOWN_SENSOR, Hid_mouse_report_click_left, Hid_mouse_report_click_right, Hid_mouse_report_down, Hid_mouse_report_left, Hid_mouse_report_right, Hid_mouse_report_up, LCLICK_SENSOR, LEFT_SENSOR, NO_SENSOR, RCLICK_SENSOR, RIGHT_SENSOR, and UP_SENSOR.
Referenced by Button_wait_func(), Default_func(), Inc_speed(), Maybe_left_holddown(), Mov_count_func(), Mov_press_func(), and Mov_touch_func().
{
   switch(sensor) {
      case NO_SENSOR : // No action
         break;
      case UP_SENSOR : // PF1
         Hid_mouse_report_up();
         break;
      case LEFT_SENSOR : // PF2
         Hid_mouse_report_left();
         break;
      case RIGHT_SENSOR : // PF4
         Hid_mouse_report_right();
         break;
      case DOWN_SENSOR : // PF5
         Hid_mouse_report_down();
         break;
      case RCLICK_SENSOR : // PF6
         Hid_mouse_report_click_right();
         break;
      case LCLICK_SENSOR : // PF7
         Hid_mouse_report_click_left();
         break;
   }
}
Variable Documentation
trigges ved å holde nede venstre museknapp Scroll trigges ved å holde nede høyre museknapp ikke bare den første Movement Countdown Movement Press Movement Touch State = DEFAULT_STATE
State variable, to memorize across tasks.
Definition at line 17 of file sensors.c.
Referenced by Button_wait_func(), Default_func(), is_mouse_event(), Mov_count_func(), Mov_press_func(), Mov_touch_func(), and Scroll_func().
U16 State_counter = 0
Generic global counter to stay in a state a number of tasks.
Remember to reset before changing state!
Definition at line 21 of file sensors.c.
Referenced by Button_wait_func(), Default_func(), Maybe_slow_cursor(), Mov_count_func(), Mov_touch_func(), and Scroll_func().
bit Slow_cursor = FALSE
If TRUE, cursor speed may be decreased by skipping tasks.
Definition at line 24 of file sensors.c.
Referenced by Default_func(), Maybe_slow_cursor(), Mov_count_func(), and Mov_touch_func().
bit Left_holddown = FALSE
If TRUE, the left mouse button is held down.
Definition at line 27 of file sensors.c.
Referenced by Button_wait_func(), Default_func(), Maybe_left_holddown(), and Mov_touch_func().
bit Report_filled = FALSE
If TRUE, there is a mouse event.
This is the value returned by is_mouse_event.
Definition at line 31 of file sensors.c.
Referenced by is_mouse_event(), and Maybe_left_holddown().
U8 g_hid_mouse_report[4]
Mouse report, defined in mouse_task.c.
Definition at line 65 of file mouse_task.c.
Referenced by Maybe_slow_cursor(), and mouse_task().
U8 Zerovalue[8] = {0}
Calibration values of sensors (i.e., reference level).
Reference level for steps, defined in sensors.c.
Definition at line 37 of file sensors.c.
Referenced by Calibrate(), is_sensor_step(), and mouse_task_init().
U8 Invalue[8] = {0}
Read values of sensors, to be compared against the calibration values.
Definition at line 40 of file sensors.c.
Referenced by Calibrate(), is_more_active(), is_sensor_step(), and Read_sensors().
U8 Active_sensor = 0
Number of currently active sensor.
Definition at line 43 of file sensors.c.
Referenced by Button_wait_func(), Default_func(), Mov_count_func(), Mov_press_func(), Mov_touch_func(), and Scroll_func().
U8 Neighbor_sensor = 0
Number of active neighbor sensor.
Definition at line 46 of file sensors.c.
Referenced by Default_func(), and Mov_press_func().
bit Nearby_sensors[8][8]
Initial value:
 {{0, 0, 0, 0, 0, 0, 0, 0},
                            {0, 0, 1, 0, 1, 0, 0, 0},
                            {0, 1, 0, 0, 0, 1, 0, 0},
                            {0, 0, 0, 0, 0, 0, 0, 0},
                            {0, 0, 1, 0, 0, 1, 0, 0},
                            {0, 0, 0, 0, 0, 0, 0, 0},
                            {0, 0, 0, 0, 0, 1, 0, 1},
                            {0, 0, 0, 0, 0, 1, 1, 0}}
Matrix of adjacent sensors.
(PF0 and PF3 are temp. sensors and are disabled.)
Definition at line 52 of file sensors.c.
Referenced by check_nearby_sensor().