---
title: "q Quotes 1.0.13"
show-title: false
show-nav: false
stylesheet:
  - /_assets/css/libertine.css
  - /_assets/css/gothic.css
  - style.css
index:
  "q Quotes": .
  "`q` Quotes": .
plain: true
---
