var prism = require('markdown-it-prism');

// require('prismjs/components/prism-abap.js');
// require('prismjs/components/prism-actionscript.js');
// require('prismjs/components/prism-ada.js');
// require('prismjs/components/prism-apacheconf.js');
// require('prismjs/components/prism-apl.js');
// require('prismjs/components/prism-applescript.js');
// require('prismjs/components/prism-arduino.js');
// require('prismjs/components/prism-arff.js');
// require('prismjs/components/prism-asciidoc.js');
// require('prismjs/components/prism-asm6502.js');
// require('prismjs/components/prism-aspnet.js');
// require('prismjs/components/prism-autohotkey.js');
// require('prismjs/components/prism-autoit.js');
require('prismjs/components/prism-bash.js');
// require('prismjs/components/prism-basic.js');
// require('prismjs/components/prism-batch.js');
// require('prismjs/components/prism-bison.js');
// require('prismjs/components/prism-brainfuck.js');
// require('prismjs/components/prism-bro.js');
require('prismjs/components/prism-c.js');
// require('prismjs/components/prism-clike.js');
// require('prismjs/components/prism-clojure.js');
// require('prismjs/components/prism-coffeescript.js');
// require('prismjs/components/prism-core.js');
require('prismjs/components/prism-cpp.js');
// require('prismjs/components/prism-crystal.js');
require('prismjs/components/prism-csharp.js');
// require('prismjs/components/prism-csp.js');
require('prismjs/components/prism-css.js');
require('prismjs/components/prism-css-extras.js');
// require('prismjs/components/prism-d.js');
// require('prismjs/components/prism-dart.js');
// require('prismjs/components/prism-diff.js');
// require('prismjs/components/prism-django.js');
// require('prismjs/components/prism-docker.js');
// require('prismjs/components/prism-eiffel.js');
// require('prismjs/components/prism-elixir.js');
// require('prismjs/components/prism-elm.js');
// require('prismjs/components/prism-erb.js');
// require('prismjs/components/prism-erlang.js');
// require('prismjs/components/prism-flow.js');
// require('prismjs/components/prism-fortran.js');
// require('prismjs/components/prism-fsharp.js');
// require('prismjs/components/prism-gedcom.js');
// require('prismjs/components/prism-gherkin.js');
// require('prismjs/components/prism-git.js');
// require('prismjs/components/prism-glsl.js');
// require('prismjs/components/prism-go.js');
// require('prismjs/components/prism-graphql.js');
// require('prismjs/components/prism-groovy.js');
// require('prismjs/components/prism-haml.js');
// require('prismjs/components/prism-handlebars.js');
require('prismjs/components/prism-haskell.js');
// require('prismjs/components/prism-haxe.js');
// require('prismjs/components/prism-hpkp.js');
// require('prismjs/components/prism-hsts.js');
// require('prismjs/components/prism-http.js');
// require('prismjs/components/prism-ichigojam.js');
// require('prismjs/components/prism-icon.js');
// require('prismjs/components/prism-inform7.js');
// require('prismjs/components/prism-ini.js');
// require('prismjs/components/prism-io.js');
// require('prismjs/components/prism-j.js');
require('prismjs/components/prism-java.js');
require('prismjs/components/prism-javascript.js');
// require('prismjs/components/prism-jolie.js');
// require('prismjs/components/prism-json.js');
require('prismjs/components/prism-jsx.js');
// require('prismjs/components/prism-julia.js');
// require('prismjs/components/prism-keyman.js');
// require('prismjs/components/prism-kotlin.js');
// require('prismjs/components/prism-latex.js');
// require('prismjs/components/prism-less.js');
// require('prismjs/components/prism-liquid.js');
// require('prismjs/components/prism-lisp.js');
// require('prismjs/components/prism-livescript.js');
// require('prismjs/components/prism-lolcode.js');
// require('prismjs/components/prism-lua.js');
// require('prismjs/components/prism-makefile.js');
require('prismjs/components/prism-markdown.js');
// require('prismjs/components/prism-markup-templating.js');
// require('prismjs/components/prism-markup.js');
// require('prismjs/components/prism-matlab.js');
// require('prismjs/components/prism-mel.js');
// require('prismjs/components/prism-mizar.js');
// require('prismjs/components/prism-monkey.js');
// require('prismjs/components/prism-n4js.js');
// require('prismjs/components/prism-nasm.js');
// require('prismjs/components/prism-nginx.js');
// require('prismjs/components/prism-nim.js');
// require('prismjs/components/prism-nix.js');
// require('prismjs/components/prism-nsis.js');
// require('prismjs/components/prism-objectivec.js');
// require('prismjs/components/prism-ocaml.js');
// require('prismjs/components/prism-opencl.js');
// require('prismjs/components/prism-oz.js');
// require('prismjs/components/prism-parigp.js');
// require('prismjs/components/prism-parser.js');
// require('prismjs/components/prism-pascal.js');
// require('prismjs/components/prism-perl.js');
// require('prismjs/components/prism-php.js');
// require('prismjs/components/prism-php-extras.js');
// require('prismjs/components/prism-plsql.js');
require('prismjs/components/prism-powershell.js');
// require('prismjs/components/prism-processing.js');
// require('prismjs/components/prism-prolog.js');
// require('prismjs/components/prism-properties.js');
// require('prismjs/components/prism-protobuf.js');
// require('prismjs/components/prism-pug.js');
// require('prismjs/components/prism-puppet.js');
// require('prismjs/components/prism-pure.js');
require('prismjs/components/prism-python.js');
// require('prismjs/components/prism-q.js');
// require('prismjs/components/prism-qore.js');
require('prismjs/components/prism-r.js');
// require('prismjs/components/prism-reason.js');
// require('prismjs/components/prism-renpy.js');
// require('prismjs/components/prism-rest.js');
// require('prismjs/components/prism-rip.js');
// require('prismjs/components/prism-roboconf.js');
// require('prismjs/components/prism-ruby.js');
// require('prismjs/components/prism-rust.js');
// require('prismjs/components/prism-sas.js');
// require('prismjs/components/prism-sass.js');
// require('prismjs/components/prism-scala.js');
require('prismjs/components/prism-scheme.js');
// require('prismjs/components/prism-scss.js');
// require('prismjs/components/prism-smalltalk.js');
// require('prismjs/components/prism-smarty.js');
// require('prismjs/components/prism-soy.js');
// require('prismjs/components/prism-sql.js');
// require('prismjs/components/prism-stylus.js');
// require('prismjs/components/prism-swift.js');
// require('prismjs/components/prism-tap.js');
// require('prismjs/components/prism-tcl.js');
// require('prismjs/components/prism-textile.js');
// require('prismjs/components/prism-tsx.js');
// require('prismjs/components/prism-tt2.js');
// require('prismjs/components/prism-twig.js');
require('prismjs/components/prism-typescript.js');
// require('prismjs/components/prism-vbnet.js');
// require('prismjs/components/prism-velocity.js');
// require('prismjs/components/prism-verilog.js');
// require('prismjs/components/prism-vhdl.js');
// require('prismjs/components/prism-vim.js');
// require('prismjs/components/prism-visual-basic.js');
// require('prismjs/components/prism-wasm.js');
// require('prismjs/components/prism-wiki.js');
// require('prismjs/components/prism-xeora.js');
// require('prismjs/components/prism-xojo.js');
// require('prismjs/components/prism-xquery.js');
require('prismjs/components/prism-yaml.js');

require('prismjs/plugins/line-highlight/prism-line-highlight.js');

module.exports = prism;
